### ISSUE TITLE
Buff Powersword

### ISSUE THREAD

**Issue by vborovin** [sm-augmented/hub#11]
(Lupus):
Argumentation: 
PS is the single worst option

Every other weapon outclasses it in nearly every single way.
It's whole gimic is being anti-armor. Well, it does that poorly, and the power axe is just the power sword but better in every way outside of swing speed. 

The chainsword is just better due to being able to one shot a boy (with bleed) and the fact that it's zeal heals more than the pitiful amount of health and armor the power sword gets, makes the PS a joke
Not even to bring up the power fist, which outside of not having a zeal, is just better in everyway, matching it's swing speed even.

With some testing of numbers, I can explain why I dislike the powersword now.
Not one of it's normal swings can cleave a standard Boy, or the lower health Shoota Boy in two. The Only time you can oneshot a standard boy, is with the medium jump swing. Shoota boys can only be oneshot by the powersword on it's third or fourth swing, but neither of this swings can oneshot a standard boy.

For additional context, the chainsword's first swing is not able to directly oneshot a boy. However, it's bleed kills them after about four ticks. Meaning the damage on the swing is already higher than powersword's swing. 
The powersword is intended as an anti-armor weapon, but deals less damage against 'Ard Boyz shields, than  it does against standard boys. This doesn't make a lot of sense to me at least.

Proposed solution:
Powersword damage as it stands: 66 for the first two swings. 70 for the third and 80 for the fourth. All of these numbers should go up by about 20 (or 19) to make one shotting Boyz possible, and thus not feel as bad. 
(The DFA attack is fine as is, it deals something like 80 ish damage, I had a hard time finding it's number, but it seemed to one-shot boys.) 

Current Damage: 66 / 66 / 70 / 80
Suggested damage change: 86 / 86 / 90 / 100 

The damage reduction applied to it's swings against armor (Like 'Ard Boyz shields) Could go further down, if not allowing it to deal full damage against armored targets. This wont step on the toes of the power axe too much, as the Axe should still be better over all. 

-Zeal-
The only other thing I personally wouldn't mind seeing changed is the Zeal. As it's not great. I think the best solution (if this is to be modified) is to give it higher armor bits than health. Similar to the Axe, but maybe a bit more armor and less health with out the armor regen that the Axe's zeal has. 

Alternatively the zeal remains as is, but each swing starts armor regen, maybe with a small bump to the armor gained per swing.

-PWMK-
Leave as is

**Comment by vborovin** [comment]
Drawbacks:
According to Dragonik's words, PS is meant to be team support option but isn't properly used in that role, which leads to misunderstanding issues.

**Comment by Akta-warpsmit** [comment]
I believe that splitting the damage of melee weapons, following the example of ranged weapons, will partially solve this problem.

**Comment by vborovin** [comment]
> I believe that splitting the damage of melee weapons, following the example of ranged weapons, will partially solve this problem.
What do you mean by splitting the damage?

**Comment by Akta-warpsmit** [comment]
> > Я считаю, что разделение урона оружия ближнего боя по примеру оружия дальнего боя частично решит эту проблему.
> 
> Что вы имеете в виду под разделением ущерба?
I mean hit damage and armor damage.

**Comment by vborovin** [comment]
> I mean damage to hp and armor.
Расскажи поподробнее, Сейчас у всего оружия, и ближнего, и дальнего, отличается урон по хп и броне, и в зависимости от частей тела, бронированности и тд.

**Comment by Akta-warpsmit** [comment]
> Расскажи поподробнее, Сейчас у всего оружия, и ближнего, и дальнего, отличается урон по хп и броне, и в зависимости от частей тела, бронированности и тд.
В таком случае, увеличивать весь урон, и по хп и по броне.
