### ISSUE TITLE
Take Volkite From PvP

### ISSUE THREAD

**Issue by vborovin** [sm-augmented/hub#18]
(Lupus):
Steal Volkite from PvP and make its heavier versions

**Comment by Akta-warpsmit** [comment]
Видение волкит випон не изменилось?

**Comment by vborovin** [comment]
> Видение волкит випон не изменилось?

Люпус предложил взять серпенту из ПвП, адаптировать и расширить на более тяжелые версии. Но это только предложение. Очень сильно отличается от концепта который задумывался Драгоником

**Comment by Akta-warpsmit** [comment]
> Люпус предложил взять серпенту из ПвП, принять и расширить на более тяжелую версию. Но это только предложение. Очень сильно отличается от концепции, которая задумывалась Драгоником

Какая концепция была у Драгоника?

**Comment by Akta-warpsmit** [comment]
> Люпус предложил взять серпенту из ПвП, принять и расширить на более тяжелую версию. Но это только предложение. Очень сильно отличается от концепции, которая задумывалась Драгоником

Какая концепция была у Драгоника?
