### ISSUE TITLE
Align TH DFA Attack Damage w/ Main Attack Damage

### ISSUE THREAD

**Issue by vborovin** [sm-augmented/hub#8]
(Lupus)
Description:
That particular DFA attack deals either 40 damage on the low end, or 60 damage. But the normal swing deals 85
Personally, I don't see a reason for the DFA attack to not be able to one shot a boy

Proposed solution:
Align this attack damage with first attack damage
Also make it affected by KB

**Comment by Akta-warpsmit** [comment]
DFA - это топот?

**Comment by vborovin** [comment]
> DFA - это топот?

Нет, это атака после смерти с небес, но которая короткая
